version: '3.8'

services:
  web:
    # Build the Dockerfile in the current directory
    build: .
    # Map port 80 on the host to port 80 in the container
    ports:
      - "80:80"
      - "443:443"
